name: Create UCD Component Version

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Create Component Version
      uses: tpneal/UCDCreateVersionAction@v1.1
      with:
        component: 'ArgoCD'
        versionname: 'v1'
        description: 'Version 1 of ArgoCD'
        type: 'full'
        hostname: 'ucd7320-opr-ibm-ucd-prod-tneal.ucd-ocp10-e3a3d814b8ff2369cc3d5b63c99b22ba-0000.us-east.containers.appdomain.cloud'
        port: '443'
        username: 'admin'
        password: 'admin'
