name: Create UCD Component Version

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Create Component Version
      uses: tpneal/UCDCreateVersionAction@v1.24
      with:
        component: 'ArgoCD-KubeToy'
        versionname: '${{ github.event.head_commit.id }}'
        description: '${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.head_commit.id }}'
        hostname: 'ucd7320-opr-ibm-ucd-prod-tneal.ucd-ocp10-e3a3d814b8ff2369cc3d5b63c99b22ba-0000.us-east.containers.appdomain.cloud'
        port: '443'
        username: 'admin'
        password: '${{ secrets.UCD_PASSWORD }}'
        authToken: '${{ secrets.UCD_AUTHTOKEN }}'
